package br.com.msystem.biblioteca.vo;
// Generated 01/03/2012 01:28:16 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BloquearMaterialBibliografico generated by hbm2java
 */
@Entity
@Table(name="bloquear_material_bibliografico"
    ,catalog="biblioteca"
)
public class BloquearMaterialBibliografico  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -288432019482384132L;
	private Integer idBloquearMaterialBibliografico;
     private Usuario usuario;
     private MaterialBibliografico materialBibliografico;
     private Date dataBloqueio;
     private String motivoBloqueio;
     private String statusBloqueio;

    public BloquearMaterialBibliografico() {
    }

    public BloquearMaterialBibliografico(Usuario usuario, MaterialBibliografico materialBibliografico, Date dataBloqueio, String motivoBloqueio, String statusBloqueio) {
       this.usuario = usuario;
       this.materialBibliografico = materialBibliografico;
       this.dataBloqueio = dataBloqueio;
       this.motivoBloqueio = motivoBloqueio;
       this.statusBloqueio = statusBloqueio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_bloquear_material_bibliografico", unique=true, nullable=false)
    public Integer getIdBloquearMaterialBibliografico() {
        return this.idBloquearMaterialBibliografico;
    }
    
    public void setIdBloquearMaterialBibliografico(Integer idBloquearMaterialBibliografico) {
        this.idBloquearMaterialBibliografico = idBloquearMaterialBibliografico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_material_bibliografico", nullable=false)
    public MaterialBibliografico getMaterialBibliografico() {
        return this.materialBibliografico;
    }
    
    public void setMaterialBibliografico(MaterialBibliografico materialBibliografico) {
        this.materialBibliografico = materialBibliografico;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_bloqueio", nullable=false, length=19)
    public Date getDataBloqueio() {
        return this.dataBloqueio;
    }
    
    public void setDataBloqueio(Date dataBloqueio) {
        this.dataBloqueio = dataBloqueio;
    }

    
    @Column(name="motivo_bloqueio", nullable=false, length=65535)
    public String getMotivoBloqueio() {
        return this.motivoBloqueio;
    }
    
    public void setMotivoBloqueio(String motivoBloqueio) {
        this.motivoBloqueio = motivoBloqueio;
    }

    
    @Column(name="status_bloqueio", nullable=false, length=7)
    public String getStatusBloqueio() {
        return this.statusBloqueio;
    }
    
    public void setStatusBloqueio(String statusBloqueio) {
        this.statusBloqueio = statusBloqueio;
    }

	public Boolean getStatusBloqueioBoolean() {
		return this.getStatusBloqueio().equals("ativo");
	}

	public void setStatusBloqueioBoolean(Boolean statusBloqueio2) {
		if (statusBloqueio2) {
			this.setStatusBloqueio("ativo");
		} else {
			this.setStatusBloqueio("inativo");
		}
	}

}


