package br.com.msystem.biblioteca.vo;
// Generated 01/03/2012 01:28:16 by Hibernate Tools 3.4.0.CR1


import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GrupoUsuarioPermissao generated by hbm2java
 */
@Entity
@Table(name="grupo_usuario_permissao"
    ,catalog="biblioteca"
)
public class GrupoUsuarioPermissao  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -2162828051089069026L;
	private Integer idGrupoUsuarioPermissao;
     private Permissao permissao;
     private GrupoUsuario grupoUsuario;
     private Set<String> tipoPermissao;

    public GrupoUsuarioPermissao() {
    }

    public GrupoUsuarioPermissao(Permissao permissao, GrupoUsuario grupoUsuario, Set<String> tipoPermissao) {
       this.permissao = permissao;
       this.grupoUsuario = grupoUsuario;
       this.tipoPermissao = tipoPermissao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_grupo_usuario_permissao", unique=true, nullable=false)
    public Integer getIdGrupoUsuarioPermissao() {
        return this.idGrupoUsuarioPermissao;
    }
    
    public void setIdGrupoUsuarioPermissao(Integer idGrupoUsuarioPermissao) {
        this.idGrupoUsuarioPermissao = idGrupoUsuarioPermissao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_permissao", nullable=false)
    public Permissao getPermissao() {
        return this.permissao;
    }
    
    public void setPermissao(Permissao permissao) {
        this.permissao = permissao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_grupo_usuario", nullable=false)
    public GrupoUsuario getGrupoUsuario() {
        return this.grupoUsuario;
    }
    
    public void setGrupoUsuario(GrupoUsuario grupoUsuario) {
        this.grupoUsuario = grupoUsuario;
    }

    
    @Column(name="tipo_permissao", nullable=false, length=25)
    public Set<String> getTipoPermissao() {
        return this.tipoPermissao;
    }
    
    public void setTipoPermissao(Set<String> tipoPermissao) {
        this.tipoPermissao = tipoPermissao;
    }




}


