package br.com.msystem.biblioteca.vo;
// Generated 01/03/2012 01:28:16 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LocalMaterialBibliografico generated by hbm2java
 */
@Entity
@Table(name="local_material_bibliografico"
    ,catalog="biblioteca"
)
public class LocalMaterialBibliografico  implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 6913762709542063297L;

	private Integer idLocalMaterialBibliografico;
     private String descricaoLocalMaterialBibliografico;
     private Set<MaterialBibliografico> materialBibliograficos = new HashSet<MaterialBibliografico>(0);

    public LocalMaterialBibliografico() {
    }

	
    public LocalMaterialBibliografico(String descricaoLocalMaterialBibliografico) {
        this.descricaoLocalMaterialBibliografico = descricaoLocalMaterialBibliografico;
    }
    public LocalMaterialBibliografico(String descricaoLocalMaterialBibliografico, Set<MaterialBibliografico> materialBibliograficos) {
       this.descricaoLocalMaterialBibliografico = descricaoLocalMaterialBibliografico;
       this.materialBibliograficos = materialBibliograficos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_local_material_bibliografico", unique=true, nullable=false)
    public Integer getIdLocalMaterialBibliografico() {
        return this.idLocalMaterialBibliografico;
    }
    
    public void setIdLocalMaterialBibliografico(Integer idLocalMaterialBibliografico) {
        this.idLocalMaterialBibliografico = idLocalMaterialBibliografico;
    }

    
    @Column(name="descricao_local_material_bibliografico", nullable=false, length=45)
    public String getDescricaoLocalMaterialBibliografico() {
        return this.descricaoLocalMaterialBibliografico;
    }
    
    public void setDescricaoLocalMaterialBibliografico(String descricaoLocalMaterialBibliografico) {
        this.descricaoLocalMaterialBibliografico = descricaoLocalMaterialBibliografico;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="localMaterialBibliografico")
    public Set<MaterialBibliografico> getMaterialBibliograficos() {
        return this.materialBibliograficos;
    }
    
    public void setMaterialBibliograficos(Set<MaterialBibliografico> materialBibliograficos) {
        this.materialBibliograficos = materialBibliograficos;
    }




}


