package br.com.msystem.biblioteca.vo;
// Generated 01/03/2012 01:28:16 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoMaterialBibliografico generated by hbm2java
 */
@Entity
@Table(name="tipo_material_bibliografico"
    ,catalog="biblioteca"
)
public class TipoMaterialBibliografico  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -8281136499465485330L;
	private Integer idTipoMaterialBibliografico;
     private String descricaoTipoMaterialBibliografico;
     private Set<MaterialBibliografico> materialBibliograficos = new HashSet<MaterialBibliografico>(0);

    public TipoMaterialBibliografico() {
    }

	
    public TipoMaterialBibliografico(String descricaoTipoMaterialBibliografico) {
        this.descricaoTipoMaterialBibliografico = descricaoTipoMaterialBibliografico;
    }
    public TipoMaterialBibliografico(String descricaoTipoMaterialBibliografico, Set<MaterialBibliografico> materialBibliograficos) {
       this.descricaoTipoMaterialBibliografico = descricaoTipoMaterialBibliografico;
       this.materialBibliograficos = materialBibliograficos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipo_material_bibliografico", unique=true, nullable=false)
    public Integer getIdTipoMaterialBibliografico() {
        return this.idTipoMaterialBibliografico;
    }
    
    public void setIdTipoMaterialBibliografico(Integer idTipoMaterialBibliografico) {
        this.idTipoMaterialBibliografico = idTipoMaterialBibliografico;
    }

    
    @Column(name="descricao_tipo_material_bibliografico", nullable=false, length=45)
    public String getDescricaoTipoMaterialBibliografico() {
        return this.descricaoTipoMaterialBibliografico;
    }
    
    public void setDescricaoTipoMaterialBibliografico(String descricaoTipoMaterialBibliografico) {
        this.descricaoTipoMaterialBibliografico = descricaoTipoMaterialBibliografico;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoMaterialBibliografico")
    public Set<MaterialBibliografico> getMaterialBibliograficos() {
        return this.materialBibliograficos;
    }
    
    public void setMaterialBibliograficos(Set<MaterialBibliografico> materialBibliograficos) {
        this.materialBibliograficos = materialBibliograficos;
    }




}


